### PR TITLE
Track "Learn More" Conversions

### PR DESCRIPTION
**Pull request by adamsfallen**
Add GA event tracking to detect when user clicks “Learn More” for each
tool.

### CODE REVIEW

**Comment by rossdakin** [comment]
Thanks man!

Can you see if this works?

```javascript
    $('#connect').on('click', '.ood-gallery-item a', function(event) {
      var toolName = $(this).closest('.ood-gallery-item').find('header').text().trim();
      ga('send', 'event', 'opportunity', 'click', toolName);
    });
```

Just uses more general and symantec selectors in case we change the `h4` to `h5`, use a different visual style on the button, make the image clickable, etc.

Also uses event delegation to hang one event handler on the `#connect` element (rather than one each for all the `article .use-button`s, which is in theory more efficient (though admittedly negligibly so in this case).

**Comment by adamsfallen** [comment]
kk looks good :+1:

**Comment by rossdakin** [comment]
Cool — untested though (I'm on a plane and being lazy). Can you verify? I haven't written JS in almost a year :blush:

**Comment by rossdakin** [comment]
Would also be cool to track the expansion of data set and scenario
accordions if you're feeling heroic.


Ross Dakin
Presidential Innovation Fellow
whitehouse.gov/innovationfellows
(202) 286-0143
ross.dakin@pif.gov

**Comment by adamsfallen** [comment]
tested / updated.

**Comment by rossdakin** [comment]
Youdaman.

**Pull request merged**
